name: Node.js CI with SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14" # Set this to the Node.js version you're using
      - name: Install dependencies
        run: npm install
      - name: Static Code Analyasis using SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Provided by Actions, do not need to change
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_API }} # Set this to your SonarCloud token
